### ISSUE TITLE
test_assign_unassigned_client_(volunteer_side) sometimes fails 

### ISSUE THREAD

**Issue by chrysalag** [panter/aoz-003#128]
test_assign_unassigned_client_(volunteer_side)

passes locally
sometimes fails on Travis

**Comment by toupeira** [comment]
Just FYI, the tests are run in randomized order, it's possible that a test doesn't clean up properly (or has other weird side effects) which can cause a following test to fail.

You can see the seed used in the build output:

```
$ bundle exec rails test:system
Run options: --seed 36152
```

If you pass the same `--seed` locally to `rails test` you can recreate the same order.

**Comment by casaper** [comment]
These two tests need either to be fixed, or dropped!

https://github.com/panter/aoz-003/blob/develop/test/system/assignments_test.rb#L29
https://github.com/panter/aoz-003/blob/develop/test/system/assignments_test.rb#L43

It can't be the point of tests, if their just telling us bullshit about anything.
