### ISSUE TITLE
Authorization issues

### ISSUE THREAD

**Issue by toupeira** [panter/aoz-003#132]
Noticed a few issues while reviewing #126:

- Devise controller actions don't seem to be authorized at all, are we using them? (see https://github.com/elabs/pundit/issues/113)
- Calling `authorize` at the end of actions like `create` and `update` doesn't seem right, as the DB change has already been performed at this point. I guess the exception raised by Pundit will trigger a rollback, but we still have to think about other side-effects like mail notifications
- There are a lot of actions without an `authorize` call, we should probably add `after_action :verify_authorized` to more/all controllers (or `ApplicationController`)
- We're duplicating the policy logic for `new?`/`create?` and `edit?`/`update?`

I haven't worked with Pundit before so maybe I'm misunderstanding something :)

/cc @panterch @kitsane

**Comment by casaper** [comment]
👍

**Comment by casaper** [comment]
@toupeira 
> There are a lot of actions without an authorize call, we should probably add after_action :verify_authorized to more/all controllers (or ApplicationController)

But the Pundit readme says: 
> This verification mechanism only exists to aid you while developing your application, so you don't forget to call authorize. It is not some kind of failsafe mechanism or authorization mechanism. You should be able to remove these filters without affecting how your app works in any way.

**Comment by casaper** [comment]
@toupeira 
> We're duplicating the policy logic for new?/create? and edit?/update?

As far as I can see, this is the way pundit work.
https://github.com/elabs/pundit/blob/master/lib/pundit.rb#L179

There needs to be a method that has the same name as our action with a ? at the end.

**Comment by toupeira** [comment]
> This verification mechanism only exists to aid you while developing your application, so you don't forget to call authorize. It is not some kind of failsafe mechanism or authorization mechanism. You should be able to remove these filters without affecting how your app works in any way.

What it does is throw an exception if no authorization was performed during the action, so it's a helper to make sure all actions are authorized. If we have actions that don't need it we can exclude them with a `skip_before_action :verify_authorized, only: ...` (whitelist vs. blacklist approach)

> As far as I can see, this is the way pundit work.
https://github.com/elabs/pundit/blob/master/lib/pundit.rb#L179
>
> There needs to be a method that has the same name as our action with a ? at the end.

It's just the default convention, we can also do `authorize @user, :edit` in an `update` action, or in the policy call `edit?` from `update?` to DRY it up at least a bit.

**Comment by panterch** [comment]
I this something that is already actionable? If it is more the 2h work please let me know, then I create a trello story.

**Comment by toupeira** [comment]
@panterch I wanted to discuss it first, but @casaper is already on it and also [added a card](https://trello.com/c/XPhS9Uyw/57-fix-wrong-placement-of-device-authorizing-in-controllers-and-extend-policies-to-cover-all-controllers-and-actions-as-needed-devi)
